name: Deploy to Hostinger

on:
  push:
    branches:
      - main
      - master

jobs:
  web-deploy:
    name: Deploy to Hostinger FTP
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build the React App
        run: |
          cd client
          npm install
          CI=false npm run build

      - name: Cleanup node_modules before SFTP
        run: rm -rf client/node_modules

      - name: Sync files to Hostinger via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 65002
          source: "./"
          target: "/m2k-cinemas/"
